server:
  port : 8090
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/carwashdb
    username: postgres
    password: pong4006207
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 5MB

